import { useState, useEffect, useRef } from 'react';
import { supabase, LiveEventItem } from '@/lib/supabase';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/components/ui/use-toast';
import { Radio, Mic, MicOff, Square, MessageSquare, Headphones, BookOpen } from 'lucide-react';
import AgoraRTC, { IAgoraRTCClient, IMicrophoneAudioTrack } from 'agora-rtc-sdk-ng';
import TemporalLiveChat from '../live/TemporalLiveChat';
import AdminBiblePanel from './AdminBiblePanel';

const API_BASE_URL = import.meta.env.VITE_API_URL || (import.meta.env.DEV ? '' : 'https://backend-church.vercel.app');

export default function LiveEventManager() {
  const [title, setTitle] = useState('');
  const [speaker, setSpeaker] = useState('');
  const [description, setDescription] = useState('');
  const [activeEvent, setActiveEvent] = useState<LiveEventItem | null>(null);
  const [listenerCount, setListenerCount] = useState(0);
  const [isBroadcasting, setIsBroadcasting] = useState(false);
  const [isMuted, setIsMuted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState<'chat' | 'bible'>('chat');
  const { toast } = useToast();

  const clientRef = useRef<IAgoraRTCClient | null>(null);
  const localAudioTrackRef = useRef<IMicrophoneAudioTrack | null>(null);

  const fetchActiveEvent = async () => {
    try {
      const { data, error } = await supabase
        .from('live_events')
        .select('*')
        .eq('status', 'live')
        .order('started_at', { ascending: false })
        .limit(1);

      if (!error && data && data.length > 0) {
        setActiveEvent(data[0]);
      } else {
        setActiveEvent(null);
      }
    } catch (err) {
      console.error('Error fetching active live event:', err);
    }
  };

  useEffect(() => {
    fetchActiveEvent();
    const interval = setInterval(fetchActiveEvent, 5000);
    return () => {
      clearInterval(interval);
      cleanupAgora();
    };
  }, []);

  // ── Live listener count via Supabase Presence ────────────────────────────
  useEffect(() => {
    if (!activeEvent) {
      setListenerCount(0);
      return;
    }

    const presenceChannel = supabase.channel(`live_listeners:${activeEvent.id}`);

    presenceChannel
      .on('presence', { event: 'sync' }, () => {
        const state = presenceChannel.presenceState();
        setListenerCount(Object.keys(state).length);
      })
      .subscribe();

    return () => {
      supabase.removeChannel(presenceChannel);
    };
  }, [activeEvent?.id]);

  const cleanupAgora = async () => {
    if (localAudioTrackRef.current) {
      localAudioTrackRef.current.stop();
      localAudioTrackRef.current.close();
      localAudioTrackRef.current = null;
    }
    if (clientRef.current) {
      try {
        await clientRef.current.leave();
      } catch (e) {
        // ignore leave errors on cleanup
      }
      clientRef.current = null;
    }
    setIsBroadcasting(false);
  };

  const handleStartBroadcast = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;

    setLoading(true);
    try {
      const channelName = `tac_live_${Date.now()}`;

      // 1. Fetch Agora session token from Express Backend API
      const tokenRes = await fetch(`${API_BASE_URL}/api/agora/token`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ channelName, role: 'host' }),
      });

      if (!tokenRes.ok) {
        throw new Error('Failed to obtain streaming credentials from backend server');
      }

      const { appId, token } = await tokenRes.json();

      // 2. Create Agora RTC Client & Join with Backend Credentials
      const client = AgoraRTC.createClient({ mode: 'live', codec: 'vp8' });
      clientRef.current = client;

      await client.setClientRole('host');
      await client.join(appId, channelName, token || null, null);

      // 3. Create microphone track & publish
      const microphoneTrack = await AgoraRTC.createMicrophoneAudioTrack();
      localAudioTrackRef.current = microphoneTrack;
      await client.publish([microphoneTrack]);

      // 4. Save live event session to Supabase DB via backend/client
      const { data, error } = await supabase
        .from('live_events')
        .insert([
          {
            title,
            speaker: speaker || 'Pastor / Speaker',
            description,
            status: 'live',
            agora_channel: channelName,
          },
        ])
        .select();

      if (error) throw error;

      if (data && data.length > 0) {
        setActiveEvent(data[0]);
      }

      setIsBroadcasting(true);
      setIsMuted(false);
      toast({
        title: "Live audio broadcast started!",
        description: "Credentials generated by backend server. You are broadcasting live audio.",
      });
    } catch (error: any) {
      console.error('Error starting live broadcast:', error);
      toast({
        variant: "destructive",
        title: "Broadcast initialization error",
        description: error.message || "Failed to access microphone or connect via backend server.",
      });
      await cleanupAgora();
    } finally {
      setLoading(false);
    }
  };

  const handleEndBroadcast = async () => {
    if (!activeEvent) return;

    setLoading(true);
    try {
      await cleanupAgora();

      const { error } = await supabase
        .from('live_events')
        .update({ status: 'ended', ended_at: new Date().toISOString() })
        .eq('id', activeEvent.id);

      if (error) throw error;

      toast({
        title: "Live broadcast ended",
        description: "The live stream has been closed.",
      });

      setActiveEvent(null);
      setTitle('');
      setSpeaker('');
      setDescription('');
    } catch (error: any) {
      toast({
        variant: "destructive",
        title: "Error ending broadcast",
        description: error.message,
      });
    } finally {
      setLoading(false);
    }
  };

  const toggleMute = () => {
    if (localAudioTrackRef.current) {
      const nextMuteState = !isMuted;
      localAudioTrackRef.current.setMuted(nextMuteState);
      setIsMuted(nextMuteState);
      toast({
        title: nextMuteState ? "Microphone Muted" : "Microphone Active",
      });
    }
  };

  return (
    <div className="space-y-6">
      {/* Active Broadcast Control */}
      {activeEvent ? (
        <div className="bg-gradient-to-r from-red-900 to-red-700 text-white p-6 rounded-lg shadow-lg border border-red-500">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <span className="relative flex h-4 w-4">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-4 w-4 bg-red-500"></span>
              </span>
              <h2 className="text-2xl font-bold tracking-wide uppercase">Broadcast In Progress</h2>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs bg-black/40 px-3 py-1 rounded-full font-mono flex items-center gap-1.5">
                <Headphones className="w-3.5 h-3.5 text-church-secondary" />
                {listenerCount} listening
              </span>
              <span className="text-xs bg-black/40 px-3 py-1 rounded-full font-mono">
                Channel: {activeEvent.agora_channel}
              </span>
            </div>
          </div>

          <div className="bg-black/30 p-4 rounded-md mb-6 space-y-1">
            <h3 className="text-xl font-bold text-yellow-300">{activeEvent.title}</h3>
            <p className="text-sm text-gray-200">Speaker: {activeEvent.speaker || 'Admin'}</p>
            {activeEvent.description && (
              <p className="text-xs text-gray-300 italic">{activeEvent.description}</p>
            )}
          </div>

          <div className="flex flex-wrap gap-4 items-center justify-between">
            <div className="flex items-center gap-3">
              <Button
                type="button"
                onClick={toggleMute}
                variant={isMuted ? "destructive" : "secondary"}
                className="font-semibold"
              >
                {isMuted ? <MicOff className="w-5 h-5 mr-2" /> : <Mic className="w-5 h-5 mr-2" />}
                {isMuted ? "Unmute Mic" : "Mute Mic"}
              </Button>
            </div>

            <Button
              type="button"
              onClick={handleEndBroadcast}
              disabled={loading}
              className="bg-red-950 hover:bg-black text-white font-bold px-6 border border-red-400"
            >
              <Square className="w-5 h-5 mr-2 text-red-500 fill-current" />
              End Broadcast
            </Button>
          </div>

          {/* Admin panel tabs: Live Chat | Bible */}
          <div className="mt-8 pt-6 border-t border-white/20">
            {/* Tab header */}
            <div className="flex gap-2 mb-4">
              <button
                onClick={() => setActiveTab('chat')}
                className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-colors ${
                  activeTab === 'chat'
                    ? 'bg-white text-church-primary shadow'
                    : 'bg-white/10 text-white hover:bg-white/20'
                }`}
              >
                <MessageSquare className="w-4 h-4" />
                Live Chat
              </button>
              <button
                onClick={() => setActiveTab('bible')}
                className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-colors ${
                  activeTab === 'bible'
                    ? 'bg-amber-400 text-amber-900 shadow'
                    : 'bg-white/10 text-white hover:bg-white/20'
                }`}
              >
                <BookOpen className="w-4 h-4" />
                Bible
              </button>
            </div>

            {/* Tab content */}
            {activeTab === 'chat' ? (
              <div className="bg-white text-gray-900 rounded-lg p-3">
                <TemporalLiveChat eventId={activeEvent.id} userName="Admin (Host)" />
              </div>
            ) : (
              <div className="bg-white text-gray-900 rounded-lg p-4">
                <div className="flex items-center gap-2 mb-4">
                  <BookOpen className="w-5 h-5 text-amber-600" />
                  <h4 className="font-bold text-amber-800">Post a Scripture to Live Chat</h4>
                </div>
                <AdminBiblePanel eventId={activeEvent.id} userName="Admin (Host)" />
              </div>
            )}
          </div>
        </div>
      ) : (
        /* Create New Live Event Form */
        <div className="bg-white p-6 rounded-lg shadow">
          <div className="flex items-center gap-3 mb-4">
            <Radio className="w-7 h-7 text-church-primary animate-pulse" />
            <h2 className="text-2xl font-bold text-church-primary">Start Live Audio Stream</h2>
          </div>

          <form onSubmit={handleStartBroadcast} className="space-y-4">
            <div>
              <Label htmlFor="title">Event / Sermon Title</Label>
              <Input
                id="title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="e.g. Sunday Morning Live Worship & Sermon"
                required
              />
            </div>

            <div>
              <Label htmlFor="speaker">Speaker / Preacher Name</Label>
              <Input
                id="speaker"
                value={speaker}
                onChange={(e) => setSpeaker(e.target.value)}
                placeholder="e.g. Apostle J. K. Atinyo"
              />
            </div>

            <div>
              <Label htmlFor="description">Event Description (Optional)</Label>
              <Textarea
                id="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Brief details about today's live audio service..."
              />
            </div>

            <Button
              type="submit"
              disabled={loading}
              className="w-full bg-red-600 hover:bg-red-700 text-white font-bold py-3 text-lg"
            >
              <Radio className="w-5 h-5 mr-2 animate-ping" />
              {loading ? 'Starting Broadcast via Backend...' : 'Start Live Audio Event'}
            </Button>
          </form>
        </div>
      )}
    </div>
  );
}
